# Generated by Django 6.1.1 on 2026-09-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='Bus Number (e.g. 20, 10H, 218)', max_length=50, unique=True)),
                ('route_name', models.CharField(help_text='Short route summary (e.g. Miyapur to Secunderabad)', max_length=200)),
                ('first_bus_time', models.TimeField(help_text='Time of first bus service (e.g. 05:30:00)')),
                ('last_bus_time', models.TimeField(help_text='Time of last bus service (e.g. 22:45:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this bus service currently operating?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bus stop (e.g. Ameerpet)', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional short code (e.g. AMP)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Sequence index of the stop on this route (1, 2, 3...)')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='bus_finder.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_buses', to='bus_finder.stop')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('bus', 'stop')},
            },
        ),
    ]
